---
name: HideMailto
---
SilverStripe\Security\Member:
    extensions:
        - Sunnysideup\HideMailto\HideMailtoRole
SilverStripe\CMS\Model\SiteTree:
    extensions:
        - Sunnysideup\HideMailto\HideMailto
Sunnysideup\HideMailto\HideMailto:
    email_field: Email
